name: Update major version tag

on:
  push:
    tags: ["v[0-9]+.*"]

jobs:
  update-tag:
    name: Update major version tag
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup git user
        shell: bash
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update major version tag
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          TAG=$(echo "$VERSION" | grep -Eo 'v[0-9]+')
          git tag -fa "$TAG" "$VERSION" -m "Set $TAG tag to $VERSION"
          git push -f origin "$TAG"
